---
- name: Load files 
  template:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
  with_items:
    - {src: nginx.conf.j2, dest: /etc/nginx/nginx.conf}
    - {src: virtualhost.conf.j2, dest: /etc/nginx/conf.d/virtualhost.conf}
  notify:
  - Reload nginx